# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2016 Google, Inc

obj-$(CONFIG_ARCH_ASPEED) += cpuinfo.o ast_wdt.o
obj-$(CONFIG_ASPEED_GENERIC_BOARD) += board.o
obj-$(CONFIG_ASPEED_AST2500) += ast2500/
obj-$(CONFIG_ASPEED_AST2600) += ast2600/
