#ifndef _ASM_ASPEED_SPL_H_
#define _ASM_ASPEED_SPL_H_

enum {
	BOOT_DEVICE_RAM,
	BOOT_DEVICE_MMC1,
	BOOT_DEVICE_MMC2,
	BOOT_DEVICE_MMC2_2,
	BOOT_DEVICE_NAND,
	BOOT_DEVICE_ONENAND,
	BOOT_DEVICE_NOR,
	BOOT_DEVICE_UART,
	BOOT_DEVICE_SPI,
	BOOT_DEVICE_USB,
	BOOT_DEVICE_SATA,
	BOOT_DEVICE_I2C,
	BOOT_DEVICE_BOARD,
	BOOT_DEVICE_DFU,
	BOOT_DEVICE_XIP,
	BOOT_DEVICE_BOOTROM,
	BOOT_DEVICE_NONE,

	ASPEED_BOOT_DEVICE_RAM,
	ASPEED_BOOT_DEVICE_MMC,
	ASPEED_BOOT_DEVICE_UART,
	ASPEED_SECBOOT_DEVICE_RAM,
	ASPEED_SECBOOT_DEVICE_MMC,
	ASPEED_SECBOOT_DEVICE_UART,
};

#endif
