# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) ASPEED Technology Inc.
#
# https://spdx.org/licenses


obj-$(CONFIG_CMD_NETTEST) += nettest/
obj-$(CONFIG_CMD_DRAMTEST) += dramtest.o
obj-$(CONFIG_CMD_PECITEST) += peci.o
obj-$(CONFIG_CMD_PLLTEST) += plltest.o
obj-$(CONFIG_CMD_DPTEST) += dptest.o