#
# (C) Copyright 2016-present
# ASPEED and OpenBMC development.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y = cpu.o
obj-y += ../../ast-common/watchdog.o
obj-y += ../../ast-common/timer.o
obj-y += ../../ast-common/reset.o
