#
# (C) Copyright 2016-present
# ASPEED and OpenBMC development.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y = timer.o

# It seems with newer SDKs the reset implementation is not included.
#obj-y += reset.o
